In [126]:
#Linear Regression (erro > 25%)
from sklearn.linear_model import LinearRegression
import numpy as np

# Limite de erro percentual
error_threshold = 0.25

lin_reg = LinearRegression()
lin_reg.fit(X, y)

y_pred = lin_reg.predict(X)

# Erro percentual
percent_error = np.abs(y - y_pred) / np.abs(y)

# Índices removidos
removed_idx_lr = percent_error[percent_error > error_threshold].index

# Índices mantidos
kept_idx_lr = percent_error[percent_error <= error_threshold].index

print("Linear Regression")
print(f"Amostras removidas (>25% erro): {len(removed_idx_lr)}")
print(f"Amostras mantidas: {len(kept_idx_lr)}")

display(df.loc[kept_idx_lr])

Linear Regression
Amostras removidas (>25% erro): 58
Amostras mantidas: 233

,Tipo do concreto,fck (resistência) [MPa],l (comprimento) [mm],d (diâmetro [mm],l/d (fator de forma,Teor de fibra (%),N (ganchos),"fR,1 (N/mm²) (experimental)","fR,3 (N/mm²) (experimental)",Unnamed: 13,Unnamed: 14,Unnamed: 15
0,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.99000,3.32000,4.76991,0.04411,False
1,AM-0.8-EH1,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.44000,5.68000,8.02504,0.07863,False
2,AM-0.4-EH2,63.60000,60,0.89996,66.67000,0.40000,1.00000,5.35000,5.53000,4.92472,0.07949,False
3,AM-0.8-EH2,58.70000,60,0.89996,66.67000,0.80000,1.00000,7.94000,8.78000,7.83153,0.01366,False
4,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.49000,3.03000,4.76991,0.13116,False
5,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.37000,3.28000,4.76991,0.09151,False
6,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.67000,2.98000,4.76991,0.02139,False
7,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.22000,3.06000,4.76991,0.08622,False
8,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.74000,3.50000,4.76991,0.00631,False
9,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.46000,4.09000,4.76991,0.12639,False
10,AM-0.4-EH,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.93000,3.33000,4.76991,0.03247,False
11,AM-0.8-EH,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.46000,5.68000,8.02504,0.07574,False
12,"0.5FF320MPA, 2",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.12800,4.70400,3.52328,0.14649,False
13,"0.5FF320MPA, 3",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.10880,4.52160,3.52328,0.14250,False
14,"1.0FF320MPA, 1",22.00000,50,0.74627,67.00000,1.00000,1.00000,6.74880,7.32480,5.81758,0.13798,False
15,"1.0FF320MPA, 4",22.00000,50,0.74627,67.00000,1.00000,1.00000,5.78880,5.50080,5.81758,0.00497,False
16,"0.5FF330MPA, 2",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.01120,6.04800,4.77150,0.04783,False
17,"0.5FF330MPA, 3",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.49120,6.63360,4.77150,0.13106,False
18,"0.5FF330MPA, 4",42.00000,50,0.74627,67.00000,0.50000,1.00000,6.06720,7.49760,4.77150,0.21356,erro alto
19,"1.0FF330MPA, 1",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.07200,9.55200,7.87862,0.13155,False
20,"1.0FF330MPA, 2",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.83200,9.51360,7.87862,0.10795,False
21,"1.0FF330MPA, 3",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.64960,8.37120,7.87862,0.08914,False
22,"1.0FF330MPA, 4",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.23520,9.53280,7.87862,0.14689,False
23,"0.5FS720MPA, 1",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.11040,3.12000,3.54454,0.13958,False
24,"0.5FS720MPA, 2",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.75520,2.64000,3.54454,0.28649,erro alto
25,"0.5FS720MPA, 3",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.37920,3.40800,3.54454,0.04893,False
26,"0.5FS720MPA, 4",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.98560,2.89920,3.54454,0.18721,False
27,"1.0FS720MPA, 1",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.71200,5.12640,5.85268,0.02463,False
28,"1.0FS720MPA, 2",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.40480,5.10720,5.85268,0.08287,False
29,"1.0FS720MPA, 3",24.00000,33,0.55000,60.00000,1.00000,1.00000,6.01280,4.67840,5.85268,0.02663,False
30,"1.0FS720MPA, 4",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.79840,5.37600,5.85268,0.00936,False
34,"1.0FS730MPA, 1",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.50400,9.60000,7.85945,0.17304,False
35,"1.0FS730MPA, 2",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.55200,10.70400,7.85945,0.17719,False
36,"1.0FS730MPA, 3",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.21600,9.59040,7.85945,0.14719,False
37,"1.0FS730MPA, 4",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.42400,9.96480,7.85945,0.16602,False
38,"0.5FS3N20MPA, 2",22.00000,33,0.75000,44.00000,0.50000,1.00000,3.20640,3.06240,3.08579,0.03762,False
39,"0.5FS3N20MPA, 3",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.64960,2.62080,3.08579,0.16462,False
40,"0.5FS3N20MPA, 4",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.63040,2.74560,3.08579,0.17313,False
41,"0.5FS3N30MPA, 1",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.72480,4.65600,3.93783,0.05719,False
42,"0.5FS3N30MPA, 2",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.36960,4.60800,3.93783,0.16863,False
43,"0.5FS3N30MPA, 3",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.69600,5.36640,3.93783,0.06543,False
44,"0.5FS3N30MPA, 4",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.84960,3.99360,3.93783,0.02292,False
45,"1.0FS3N30MPA, 1",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.99040,3.34080,6.33480,0.05749,False
46,"1.0FS3N30MPA, 2",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.76000,3.76320,6.33480,0.09979,False
47,"1.0FS3N30MPA, 3",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.98400,3.91680,6.33480,0.05862,False
48,"1.0FS3N30MPA, 4",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.55200,6.79680,6.33480,0.14099,False
49,M32,38.60000,60,0.90000,66.66667,0.25000,1.00000,2.38000,2.76000,2.77321,0.16521,False
50,M34,37.30000,60,0.90000,66.66667,0.50000,1.00000,5.29000,7.00000,4.50608,0.14819,False
51,M36,36.00000,60,0.90000,66.66667,0.75000,1.00000,7.29000,8.04000,5.94259,0.18483,False
52,M38,41.10000,60,0.90000,66.66667,1.00000,1.00000,6.82000,9.51000,7.78672,0.14175,False
53,H32,46.10000,60,0.90000,66.66667,0.25000,1.00000,3.31000,3.78000,3.01404,0.08942,False
54,H34,46.70000,60,0.90000,66.66667,0.50000,1.00000,6.21000,7.54000,5.00700,0.19372,False
55,H36,48.00000,60,0.90000,66.66667,0.75000,1.00000,6.61000,8.22000,6.80099,0.02889,False
56,H38,48.50000,60,0.90000,66.66667,1.00000,1.00000,8.29000,9.76000,8.41542,0.01513,False
57,H34A,47.60000,60,0.75000,80.00000,0.50000,1.00000,6.23000,7.88000,5.35096,0.14110,False
58,H34S,45.40000,35,0.55000,63.63636,0.50000,1.00000,6.06000,5.16000,4.86919,0.19650,False
61,"3D-0,37",51.00000,60,0.90000,66.66667,0.37000,1.00000,5.53000,6.25000,4.19669,0.24110,erro alto
62,"3D-0,60",49.00000,60,0.90000,66.66667,0.60000,1.00000,6.37000,6.49000,5.84329,0.08269,False
64,"4D-0,37",52.00000,60,0.90000,66.66667,0.37000,1.50000,4.76000,5.95000,4.39790,0.07607,False
67,"ABD - 0,5",48.50000,60,0.92308,65.00000,0.50000,1.00000,5.60000,4.60000,5.05608,0.09713,False
69,"LEE - 0,37",49.90000,60,0.92308,65.00000,0.37000,1.00000,5.30000,6.30000,4.12097,0.22246,erro alto
70,"LEE - 0,60",49.30000,60,0.92308,65.00000,0.60000,1.00000,6.40000,6.50000,5.81345,0.09165,False
77,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.00000,5.20000,5.09968,0.27492,erro alto
78,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.20000,5.60000,5.09968,0.21421,erro alto
80,BEN - 1,64.60000,50,0.62500,80.00000,1.00000,1.00000,11.80000,11.40000,10.19595,0.13594,False
81,BEN - 1,62.60000,50,0.62500,80.00000,1.00000,1.00000,8.00000,7.10000,10.04667,0.25583,erro alto
82,BEN - 2,62.70000,50,0.62500,80.00000,2.00000,1.00000,14.10000,15.40000,16.60132,0.17740,False
83,BEN - 2,60.80000,50,0.62500,80.00000,2.00000,1.00000,13.70000,14.30000,16.36345,0.19441,False
84,BEN - 2,64.20000,50,0.62500,80.00000,2.00000,1.00000,13.50000,13.00000,16.78642,0.24344,erro alto
85,"CUE - 0,38",24.80000,30,0.60000,50.00000,0.38000,1.00000,2.50000,2.40000,2.78638,0.11455,False
86,"CUE - 0,38",33.50000,50,1.00000,50.00000,0.38000,1.00000,2.60000,2.30000,3.20841,0.23400,erro alto
87,"CUE - 0,38",38.60000,30,0.60000,50.00000,0.38000,1.00000,3.30000,2.70000,3.42888,0.03906,False
89,"CUE - 0,64",58.30000,30,0.37975,79.00000,0.63924,1.00000,6.50000,5.40000,7.00169,0.07718,False
90,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
91,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
92,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
93,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
94,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
95,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
96,"CUE - 0,25",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
104,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
105,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
106,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
107,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
108,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
109,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
110,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
111,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
112,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
113,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
114,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
115,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
116,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
117,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
118,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
119,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
120,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
121,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
122,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
123,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
124,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
125,"POH - 0,38",45.90000,60,0.75000,80.00000,0.38000,1.00000,4.00000,2.60000,4.31313,0.07828,False
130,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.90000,3.90000,4.26324,0.09314,False
131,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,4.90000,3.10000,5.29172,0.07994,False
132,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.10000,3.80000,5.29172,0.03759,False
133,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.40000,4.30000,5.29172,0.02005,False
134,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.30000,6.80000,6.50244,0.03213,False
135,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.90000,7.50000,6.50244,0.05762,False
136,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,7.50000,8.60000,6.50244,0.13301,False
137,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,8.80000,6.70000,9.05476,0.02895,False
138,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,9.90000,7.50000,9.05476,0.08538,False
139,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,11.00000,8.60000,9.05476,0.17684,False
140,"BAR - 0,13",31.80000,60,0.75000,80.00000,0.13000,1.00000,1.70000,1.70000,1.67111,0.01699,False
141,"BAR - 0,26",31.80000,60,0.75000,80.00000,0.26000,1.00000,2.60000,2.20000,2.75931,0.06127,False
142,"BAR - 0,39",31.80000,60,0.75000,80.00000,0.39000,1.00000,3.50000,3.70000,3.70001,0.05714,False
145,"BAR - 0,45",31.80000,60,0.92308,65.00000,0.45000,1.00000,4.10000,2.40000,3.84356,0.06255,False
149,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.60000,2.60000,4.93435,0.07268,False
150,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.70000,2.70000,4.93435,0.04986,False
151,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.80000,2.80000,4.93435,0.02799,False
152,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,2.90000,4.93435,0.00701,False
153,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,3.10000,4.93435,0.00701,False
154,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,5.30000,4.10000,4.93435,0.06899,False
157,"BRG - 0,27",38.90000,60,0.75000,80.00000,0.27000,1.00000,3.10000,3.70000,3.11679,0.00541,False
158,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,4.50000,5.80000,5.04037,0.12008,False
161,"MON - 1,00",46.90000,35,0.54688,64.00000,1.00000,1.00000,8.40000,7.10000,8.17811,0.02641,False
162,"MON - 1,25",56.10000,35,0.54688,64.00000,1.25000,1.00000,8.60000,8.10000,10.45324,0.21549,erro alto
163,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.70000,2.80000,3.63882,0.34771,erro alto
164,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.60000,5.20000,4.83402,0.05087,False
165,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,5.40000,6.00000,6.49919,0.20355,erro alto
166,"TIB - 0,38",60.20000,50,0.89286,56.00000,0.38000,1.00000,4.00000,4.20000,4.37716,0.09429,False
167,"TIB - 0,57",57.80000,50,0.89286,56.00000,0.57000,1.00000,6.10000,6.70000,5.75848,0.05599,False
168,"TIB - 0,76",61.90000,50,0.89286,56.00000,0.76000,1.00000,8.10000,8.30000,7.32251,0.09599,False
169,"TIB - 0,38",43.00000,33,0.75000,44.00000,0.38000,1.00000,2.40000,2.20000,3.46446,0.44352,erro alto
170,"TIB - 0,57",41.80000,33,0.75000,44.00000,0.57000,1.00000,3.80000,3.60000,4.58429,0.20639,erro alto
171,"TIB - 0,76",40.90000,33,0.75000,44.00000,0.76000,1.00000,4.60000,4.50000,5.58769,0.21471,erro alto
172,"TIB - 0,38",60.60000,33,0.75000,44.00000,0.38000,1.00000,3.50000,3.00000,4.06929,0.16265,False
173,"TIB - 0,57",61.00000,33,0.75000,44.00000,0.57000,1.00000,5.10000,4.60000,5.47344,0.07322,False
174,"TIB - 0,76",60.00000,33,0.75000,44.00000,0.76000,1.00000,7.30000,6.30000,6.68785,0.08386,False
176,"TIB - 0,57",40.00000,50,0.74627,67.00000,0.57000,1.00000,4.70000,5.20000,5.12729,0.09091,False
177,"TIB - 0,76",47.70000,50,0.74627,67.00000,0.76000,1.00000,6.00000,6.40000,6.85709,0.14285,False
178,"TIB - 0,38",59.30000,50,0.74627,67.00000,0.38000,1.00000,4.70000,4.40000,4.59920,0.02145,False
179,"TIB - 0,57",61.10000,50,0.74627,67.00000,0.57000,1.00000,6.10000,6.30000,6.25424,0.02529,False
180,"TIB - 0,76",57.40000,50,0.74627,67.00000,0.76000,1.00000,8.00000,8.20000,7.47901,0.06512,False
182,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.90000,5.60000,4.83402,0.01346,False
183,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,6.40000,6.50000,6.49919,0.01550,False
184,"TIB - 0,38",61.20000,50,0.89286,56.00000,0.38000,1.00000,4.50000,4.80000,4.41111,0.01975,False
185,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.40000,7.00000,5.86941,0.08290,False
186,"TIB - 0,76",60.40000,50,0.89286,56.00000,0.76000,1.00000,9.20000,9.70000,7.23874,0.21318,erro alto
187,"TIB - 0,38",41.80000,50,0.74627,67.00000,0.38000,1.00000,3.90000,4.50000,3.90347,0.00089,False
188,"TIB - 0,57",40.90000,50,0.74627,67.00000,0.57000,1.00000,6.30000,6.60000,5.18107,0.17761,False
189,"TIB - 0,76",41.60000,50,0.74627,67.00000,0.76000,1.00000,7.30000,8.00000,6.43086,0.11906,False
190,"TIB - 0,38",61.10000,50,0.74627,67.00000,0.38000,1.00000,5.40000,6.10000,4.66415,0.13627,False
191,"TIB - 0,57",62.80000,50,0.74627,67.00000,0.57000,1.00000,6.90000,8.00000,6.33526,0.08185,False
192,"TIB - 0,76",60.00000,50,0.74627,67.00000,0.76000,1.00000,8.80000,9.70000,7.63603,0.13227,False
193,"TIB - 0,38",39.70000,37,0.74000,50.00000,0.38000,1.00000,2.50000,2.30000,3.47437,0.38975,erro alto
194,"TIB - 0,57",40.50000,37,0.74000,50.00000,0.57000,1.00000,3.50000,3.60000,4.70264,0.34361,erro alto
195,"TIB - 0,76",42.90000,37,0.74000,50.00000,0.76000,1.00000,5.70000,4.50000,5.94923,0.04372,False
196,"TIB - 0,38",59.00000,37,0.74000,50.00000,0.38000,1.00000,4.10000,4.00000,4.18382,0.02044,False
197,"TIB - 0,57",61.60000,37,0.74000,50.00000,0.57000,1.00000,5.10000,5.20000,5.72478,0.12251,False
198,"TIB - 0,76",60.00000,37,0.74000,50.00000,0.76000,1.00000,6.30000,6.10000,6.96292,0.10523,False
199,"TIB - 0,38",57.10000,50,0.89286,56.00000,0.38000,1.00000,4.40000,5.80000,4.26996,0.02955,False
200,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.90000,7.80000,5.86941,0.14936,False
202,"TIB - 0,38",56.60000,50,0.74627,67.00000,0.38000,1.00000,5.70000,6.60000,4.49977,0.21057,erro alto
203,"TIB - 0,57",57.40000,50,0.74627,67.00000,0.57000,1.00000,7.80000,9.40000,6.07367,0.22132,erro alto
204,"TIB - 0,76",59.60000,50,0.74627,67.00000,0.76000,1.00000,9.10000,11.00000,7.61211,0.16350,False
207,"TIB - 0,38",32.30000,50,1.00000,50.00000,0.38000,1.00000,2.10000,2.10000,3.15398,0.50190,erro alto
209,"TIB - 0,38",34.80000,44,0.97778,45.00000,0.38000,1.00000,2.40000,1.60000,3.15949,0.31645,erro alto
210,"TIB - 0,50",70.60000,30,0.37500,80.00000,0.50000,1.00000,7.30000,7.80000,6.43759,0.11814,False
211,"TIB - 1,00",71.80000,60,0.75000,80.00000,1.00000,1.00000,12.40000,11.80000,10.71399,0.13597,False
213,"TIB - 1,00",24.50000,30,0.62500,48.00000,1.00000,1.00000,5.80000,4.40000,5.50806,0.05033,False
214,"TIB - 0,50",39.30000,30,0.62500,48.00000,0.50000,1.00000,4.10000,3.40000,4.16346,0.01548,False
215,"TIB - 1,00",26.40000,30,0.62500,48.00000,1.00000,1.00000,5.40000,4.40000,5.70443,0.05638,False
216,"TIB - 1,00",33.70000,35,0.54688,64.00000,1.00000,1.00000,6.90000,6.20000,7.00376,0.01504,False
220,"TIB - 1,00",37.20000,35,0.54688,64.00000,1.00000,1.00000,9.50000,8.10000,7.33597,0.22779,erro alto
221,"TIB - 0,50",39.40000,35,0.54688,64.00000,0.50000,1.00000,5.40000,5.40000,4.56421,0.15478,False
222,"TIB - 1,00",44.50000,35,0.54688,64.00000,1.00000,1.00000,10.50000,9.20000,7.97910,0.24009,erro alto
223,"TIB - 0,50",37.60000,35,0.54688,64.00000,0.50000,1.00000,4.80000,5.20000,4.46520,0.06975,False
224,"TIB - 1,00",35.40000,35,0.54688,64.00000,1.00000,1.00000,6.80000,5.90000,7.16730,0.05401,False
225,"TIB - 0,50",41.00000,35,0.54688,64.00000,0.50000,1.00000,4.60000,4.80000,4.65022,0.01092,False
226,"TIB - 1,00",36.20000,35,0.54688,64.00000,1.00000,1.00000,7.40000,6.90000,7.24282,0.02124,False
229,"TIB - 1,00",45.10000,35,0.54688,64.00000,1.00000,1.00000,7.60000,7.00000,8.02938,0.05650,False
231,"TIB - 1,00",48.90000,80,0.80000,100.00000,1.00000,1.00000,8.30000,9.90000,9.59998,0.15662,False
232,M42,38.90000,60,0.90000,66.66667,0.25000,1.50000,3.26000,4.26000,2.89029,0.11341,False
233,M44,39.70000,60,0.90000,66.66667,0.50000,1.50000,4.89000,6.47000,4.81818,0.01469,False
234,M46,38.10000,60,0.90000,66.66667,0.75000,1.50000,6.16000,7.21000,6.33733,0.02879,False
235,M48,39.70000,60,0.90000,66.66667,1.00000,1.50000,9.08000,8.94000,7.95570,0.12382,False
236,M52,41.90000,60,0.90000,66.66667,0.25000,2.00000,3.32000,5.68000,3.14788,0.05184,False
237,M54,42.50000,60,0.90000,66.66667,0.50000,2.00000,5.42000,7.60000,5.23250,0.03459,False
238,M56,40.40000,60,0.90000,66.66667,0.75000,2.00000,6.20000,8.25000,6.85156,0.10509,False
239,M58,39.70000,60,0.90000,66.66667,1.00000,2.00000,9.35000,12.20000,8.36802,0.10502,False
240,L54,28.10000,60,0.90000,66.66667,0.50000,2.00000,4.62000,6.57000,4.30961,0.06718,False
241,H54,56.10000,60,0.90000,66.66667,0.50000,2.00000,5.51000,8.61000,5.96017,0.08170,False
242,"LEE - 0,37",49.80000,60,0.92308,65.00000,0.37000,1.50000,4.80000,6.00000,4.27537,0.10930,False
243,"LEE - 0,60",51.40000,60,0.92308,65.00000,0.60000,1.50000,6.20000,7.50000,6.15620,0.00706,False
244,"LEE - 1,00",51.70000,60,0.92308,65.00000,1.00000,1.50000,11.30000,13.60000,8.93317,0.20945,erro alto
245,"LEE - 0,37",48.00000,60,0.92308,65.00000,0.37000,2.00000,4.50000,7.50000,4.41997,0.01778,False
246,"LEE - 0,60",52.30000,60,0.92308,65.00000,0.60000,2.00000,5.60000,9.70000,6.52819,0.16575,False

In [127]:
#Random Forest (erro > 25%)
from sklearn.ensemble import RandomForestRegressor

error_threshold = 0.25

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)
rf.fit(X, y)

y_pred = rf.predict(X)

percent_error = np.abs(y - y_pred) / np.abs(y)

removed_idx_rf = percent_error[percent_error > error_threshold].index
kept_idx_rf = percent_error[percent_error <= error_threshold].index

print("Random Forest")
print(f"Amostras removidas (>25% erro): {len(removed_idx_rf)}")
print(f"Amostras mantidas: {len(kept_idx_rf)}")

display(df.loc[kept_idx_rf])

Random Forest
Amostras removidas (>25% erro): 7
Amostras mantidas: 284

,Tipo do concreto,fck (resistência) [MPa],l (comprimento) [mm],d (diâmetro [mm],l/d (fator de forma,Teor de fibra (%),N (ganchos),"fR,1 (N/mm²) (experimental)","fR,3 (N/mm²) (experimental)",Unnamed: 13,Unnamed: 14,Unnamed: 15
0,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.99000,3.32000,4.76991,0.04411,False
1,AM-0.8-EH1,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.44000,5.68000,8.02504,0.07863,False
2,AM-0.4-EH2,63.60000,60,0.89996,66.67000,0.40000,1.00000,5.35000,5.53000,4.92472,0.07949,False
3,AM-0.8-EH2,58.70000,60,0.89996,66.67000,0.80000,1.00000,7.94000,8.78000,7.83153,0.01366,False
4,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.49000,3.03000,4.76991,0.13116,False
5,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.37000,3.28000,4.76991,0.09151,False
6,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.67000,2.98000,4.76991,0.02139,False
7,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.22000,3.06000,4.76991,0.08622,False
8,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.74000,3.50000,4.76991,0.00631,False
9,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.46000,4.09000,4.76991,0.12639,False
10,AM-0.4-EH,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.93000,3.33000,4.76991,0.03247,False
11,AM-0.8-EH,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.46000,5.68000,8.02504,0.07574,False
12,"0.5FF320MPA, 2",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.12800,4.70400,3.52328,0.14649,False
13,"0.5FF320MPA, 3",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.10880,4.52160,3.52328,0.14250,False
14,"1.0FF320MPA, 1",22.00000,50,0.74627,67.00000,1.00000,1.00000,6.74880,7.32480,5.81758,0.13798,False
15,"1.0FF320MPA, 4",22.00000,50,0.74627,67.00000,1.00000,1.00000,5.78880,5.50080,5.81758,0.00497,False
16,"0.5FF330MPA, 2",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.01120,6.04800,4.77150,0.04783,False
17,"0.5FF330MPA, 3",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.49120,6.63360,4.77150,0.13106,False
18,"0.5FF330MPA, 4",42.00000,50,0.74627,67.00000,0.50000,1.00000,6.06720,7.49760,4.77150,0.21356,erro alto
19,"1.0FF330MPA, 1",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.07200,9.55200,7.87862,0.13155,False
20,"1.0FF330MPA, 2",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.83200,9.51360,7.87862,0.10795,False
21,"1.0FF330MPA, 3",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.64960,8.37120,7.87862,0.08914,False
22,"1.0FF330MPA, 4",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.23520,9.53280,7.87862,0.14689,False
23,"0.5FS720MPA, 1",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.11040,3.12000,3.54454,0.13958,False
24,"0.5FS720MPA, 2",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.75520,2.64000,3.54454,0.28649,erro alto
25,"0.5FS720MPA, 3",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.37920,3.40800,3.54454,0.04893,False
26,"0.5FS720MPA, 4",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.98560,2.89920,3.54454,0.18721,False
27,"1.0FS720MPA, 1",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.71200,5.12640,5.85268,0.02463,False
28,"1.0FS720MPA, 2",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.40480,5.10720,5.85268,0.08287,False
29,"1.0FS720MPA, 3",24.00000,33,0.55000,60.00000,1.00000,1.00000,6.01280,4.67840,5.85268,0.02663,False
30,"1.0FS720MPA, 4",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.79840,5.37600,5.85268,0.00936,False
31,"0.5FS730MPA, 1",43.00000,33,0.55000,60.00000,0.50000,1.00000,6.91200,6.94080,4.65948,0.32589,erro alto
32,"0.5FS730MPA, 2",43.00000,33,0.55000,60.00000,0.50000,1.00000,6.24960,6.34560,4.65948,0.25444,erro alto
33,"0.5FS730MPA, 3",43.00000,33,0.55000,60.00000,0.50000,1.00000,5.86560,6.60480,4.65948,0.20563,erro alto
34,"1.0FS730MPA, 1",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.50400,9.60000,7.85945,0.17304,False
35,"1.0FS730MPA, 2",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.55200,10.70400,7.85945,0.17719,False
36,"1.0FS730MPA, 3",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.21600,9.59040,7.85945,0.14719,False
37,"1.0FS730MPA, 4",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.42400,9.96480,7.85945,0.16602,False
38,"0.5FS3N20MPA, 2",22.00000,33,0.75000,44.00000,0.50000,1.00000,3.20640,3.06240,3.08579,0.03762,False
39,"0.5FS3N20MPA, 3",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.64960,2.62080,3.08579,0.16462,False
40,"0.5FS3N20MPA, 4",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.63040,2.74560,3.08579,0.17313,False
41,"0.5FS3N30MPA, 1",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.72480,4.65600,3.93783,0.05719,False
42,"0.5FS3N30MPA, 2",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.36960,4.60800,3.93783,0.16863,False
43,"0.5FS3N30MPA, 3",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.69600,5.36640,3.93783,0.06543,False
44,"0.5FS3N30MPA, 4",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.84960,3.99360,3.93783,0.02292,False
45,"1.0FS3N30MPA, 1",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.99040,3.34080,6.33480,0.05749,False
46,"1.0FS3N30MPA, 2",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.76000,3.76320,6.33480,0.09979,False
47,"1.0FS3N30MPA, 3",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.98400,3.91680,6.33480,0.05862,False
48,"1.0FS3N30MPA, 4",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.55200,6.79680,6.33480,0.14099,False
49,M32,38.60000,60,0.90000,66.66667,0.25000,1.00000,2.38000,2.76000,2.77321,0.16521,False
50,M34,37.30000,60,0.90000,66.66667,0.50000,1.00000,5.29000,7.00000,4.50608,0.14819,False
51,M36,36.00000,60,0.90000,66.66667,0.75000,1.00000,7.29000,8.04000,5.94259,0.18483,False
52,M38,41.10000,60,0.90000,66.66667,1.00000,1.00000,6.82000,9.51000,7.78672,0.14175,False
53,H32,46.10000,60,0.90000,66.66667,0.25000,1.00000,3.31000,3.78000,3.01404,0.08942,False
54,H34,46.70000,60,0.90000,66.66667,0.50000,1.00000,6.21000,7.54000,5.00700,0.19372,False
55,H36,48.00000,60,0.90000,66.66667,0.75000,1.00000,6.61000,8.22000,6.80099,0.02889,False
56,H38,48.50000,60,0.90000,66.66667,1.00000,1.00000,8.29000,9.76000,8.41542,0.01513,False
57,H34A,47.60000,60,0.75000,80.00000,0.50000,1.00000,6.23000,7.88000,5.35096,0.14110,False
58,H34S,45.40000,35,0.55000,63.63636,0.50000,1.00000,6.06000,5.16000,4.86919,0.19650,False
59,3D20,59.00000,60,0.75000,80.00000,0.25000,1.00000,2.26000,2.23000,3.58400,0.58584,erro alto
60,3D40,59.00000,60,0.75000,80.00000,0.50000,1.00000,3.79000,4.55000,5.91784,0.56144,erro alto
61,"3D-0,37",51.00000,60,0.90000,66.66667,0.37000,1.00000,5.53000,6.25000,4.19669,0.24110,erro alto
62,"3D-0,60",49.00000,60,0.90000,66.66667,0.60000,1.00000,6.37000,6.49000,5.84329,0.08269,False
63,"3D-1,0",51.00000,60,0.90000,66.66667,1.00000,1.00000,12.00000,13.31000,8.61615,0.28199,erro alto
64,"4D-0,37",52.00000,60,0.90000,66.66667,0.37000,1.50000,4.76000,5.95000,4.39790,0.07607,False
66,"ABD - 1,0",46.80000,35,0.53846,65.00000,1.00000,1.00000,5.10000,4.20000,8.20997,0.60980,erro alto
67,"ABD - 0,5",48.50000,60,0.92308,65.00000,0.50000,1.00000,5.60000,4.60000,5.05608,0.09713,False
68,"ABD - 1,0",48.20000,60,0.92308,65.00000,1.00000,1.00000,5.80000,5.10000,8.32425,0.43522,erro alto
69,"LEE - 0,37",49.90000,60,0.92308,65.00000,0.37000,1.00000,5.30000,6.30000,4.12097,0.22246,erro alto
70,"LEE - 0,60",49.30000,60,0.92308,65.00000,0.60000,1.00000,6.40000,6.50000,5.81345,0.09165,False
71,"LEE - 1,00",49.80000,60,0.92308,65.00000,1.00000,1.00000,12.00000,13.30000,8.45272,0.29561,erro alto
72,"GRI - 0,5",50.80000,50,0.74627,67.00000,0.50000,1.00000,3.70000,4.10000,5.21676,0.40994,erro alto
73,"GRI - 0,5",50.80000,50,0.74627,67.00000,0.50000,1.00000,3.40000,3.70000,5.21676,0.53434,erro alto
74,"GRI - 0,5",50.80000,50,0.74627,67.00000,0.50000,1.00000,3.20000,3.40000,5.21676,0.63024,erro alto
75,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,3.30000,4.40000,5.09968,0.54536,erro alto
76,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,3.40000,4.90000,5.09968,0.49991,erro alto
77,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.00000,5.20000,5.09968,0.27492,erro alto
78,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.20000,5.60000,5.09968,0.21421,erro alto
79,BEN - 1,66.20000,50,0.62500,80.00000,1.00000,1.00000,13.80000,11.60000,10.31362,0.25264,erro alto
80,BEN - 1,64.60000,50,0.62500,80.00000,1.00000,1.00000,11.80000,11.40000,10.19595,0.13594,False
81,BEN - 1,62.60000,50,0.62500,80.00000,1.00000,1.00000,8.00000,7.10000,10.04667,0.25583,erro alto
82,BEN - 2,62.70000,50,0.62500,80.00000,2.00000,1.00000,14.10000,15.40000,16.60132,0.17740,False
83,BEN - 2,60.80000,50,0.62500,80.00000,2.00000,1.00000,13.70000,14.30000,16.36345,0.19441,False
84,BEN - 2,64.20000,50,0.62500,80.00000,2.00000,1.00000,13.50000,13.00000,16.78642,0.24344,erro alto
85,"CUE - 0,38",24.80000,30,0.60000,50.00000,0.38000,1.00000,2.50000,2.40000,2.78638,0.11455,False
86,"CUE - 0,38",33.50000,50,1.00000,50.00000,0.38000,1.00000,2.60000,2.30000,3.20841,0.23400,erro alto
87,"CUE - 0,38",38.60000,30,0.60000,50.00000,0.38000,1.00000,3.30000,2.70000,3.42888,0.03906,False
89,"CUE - 0,64",58.30000,30,0.37975,79.00000,0.63924,1.00000,6.50000,5.40000,7.00169,0.07718,False
90,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
91,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
92,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
93,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
94,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
95,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
96,"CUE - 0,25",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
97,"CUE - 0,25",55.00000,50,1.00000,50.00000,0.25000,1.00000,2.50000,2.50000,2.99026,0.19611,False
98,"CUE - 0,38",40.70000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.51514,0.67388,erro alto
99,"CUE - 0,38",45.10000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.68852,0.75644,erro alto
100,"CUE - 0,38",45.10000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.68852,0.75644,erro alto
101,"CUE - 0,38",40.70000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.51514,0.67388,erro alto
102,"CUE - 0,38",41.60000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.55139,0.69114,erro alto
103,"CUE - 0,38",41.60000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.55139,0.69114,erro alto
104,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
105,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
106,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
107,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
108,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
109,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
110,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
111,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
112,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
113,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
114,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
115,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
116,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
117,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
118,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
119,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
120,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
121,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
122,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
123,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
124,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
125,"POH - 0,38",45.90000,60,0.75000,80.00000,0.38000,1.00000,4.00000,2.60000,4.31313,0.07828,False
126,"POH - 0,44",34.70000,60,0.75000,80.00000,0.44000,1.00000,3.00000,3.00000,4.20612,0.40204,erro alto
127,"POH - 0,5",48.50000,60,0.75000,80.00000,0.50000,1.00000,3.30000,2.40000,5.39817,0.63581,erro alto
128,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.60000,3.50000,4.26324,0.18423,False
129,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.80000,3.70000,4.26324,0.12190,False
130,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.90000,3.90000,4.26324,0.09314,False
131,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,4.90000,3.10000,5.29172,0.07994,False
132,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.10000,3.80000,5.29172,0.03759,False
133,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.40000,4.30000,5.29172,0.02005,False
134,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.30000,6.80000,6.50244,0.03213,False
135,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.90000,7.50000,6.50244,0.05762,False
136,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,7.50000,8.60000,6.50244,0.13301,False
137,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,8.80000,6.70000,9.05476,0.02895,False
138,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,9.90000,7.50000,9.05476,0.08538,False
139,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,11.00000,8.60000,9.05476,0.17684,False
140,"BAR - 0,13",31.80000,60,0.75000,80.00000,0.13000,1.00000,1.70000,1.70000,1.67111,0.01699,False
141,"BAR - 0,26",31.80000,60,0.75000,80.00000,0.26000,1.00000,2.60000,2.20000,2.75931,0.06127,False
142,"BAR - 0,39",31.80000,60,0.75000,80.00000,0.39000,1.00000,3.50000,3.70000,3.70001,0.05714,False
143,"BAR - 0,19",31.80000,60,0.92308,65.00000,0.19000,1.00000,2.60000,3.40000,2.05974,0.20779,erro alto
144,"BAR - 0,32",31.80000,60,0.92308,65.00000,0.32000,1.00000,3.90000,3.90000,3.00338,0.22990,erro alto
145,"BAR - 0,45",31.80000,60,0.92308,65.00000,0.45000,1.00000,4.10000,2.40000,3.84356,0.06255,False
146,"BAR - 0,58",31.80000,60,0.92308,65.00000,0.58000,1.00000,5.90000,5.80000,4.61822,0.21725,erro alto
148,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,3.80000,2.50000,4.93435,0.29851,erro alto
149,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.60000,2.60000,4.93435,0.07268,False
150,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.70000,2.70000,4.93435,0.04986,False
151,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.80000,2.80000,4.93435,0.02799,False
152,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,2.90000,4.93435,0.00701,False
153,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,3.10000,4.93435,0.00701,False
154,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,5.30000,4.10000,4.93435,0.06899,False
155,"BRG - 0,27",38.90000,60,0.75000,80.00000,0.27000,1.00000,2.20000,2.60000,3.11679,0.41672,erro alto
158,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,4.50000,5.80000,5.04037,0.12008,False
159,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,3.90000,5.10000,5.04037,0.29240,erro alto
160,"MON - 1,00",63.20000,60,0.75000,80.00000,1.00000,1.00000,6.50000,5.80000,10.09172,0.55257,erro alto
161,"MON - 1,00",46.90000,35,0.54688,64.00000,1.00000,1.00000,8.40000,7.10000,8.17811,0.02641,False
162,"MON - 1,25",56.10000,35,0.54688,64.00000,1.25000,1.00000,8.60000,8.10000,10.45324,0.21549,erro alto
163,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.70000,2.80000,3.63882,0.34771,erro alto
164,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.60000,5.20000,4.83402,0.05087,False
165,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,5.40000,6.00000,6.49919,0.20355,erro alto
166,"TIB - 0,38",60.20000,50,0.89286,56.00000,0.38000,1.00000,4.00000,4.20000,4.37716,0.09429,False
167,"TIB - 0,57",57.80000,50,0.89286,56.00000,0.57000,1.00000,6.10000,6.70000,5.75848,0.05599,False
168,"TIB - 0,76",61.90000,50,0.89286,56.00000,0.76000,1.00000,8.10000,8.30000,7.32251,0.09599,False
169,"TIB - 0,38",43.00000,33,0.75000,44.00000,0.38000,1.00000,2.40000,2.20000,3.46446,0.44352,erro alto
170,"TIB - 0,57",41.80000,33,0.75000,44.00000,0.57000,1.00000,3.80000,3.60000,4.58429,0.20639,erro alto
171,"TIB - 0,76",40.90000,33,0.75000,44.00000,0.76000,1.00000,4.60000,4.50000,5.58769,0.21471,erro alto
172,"TIB - 0,38",60.60000,33,0.75000,44.00000,0.38000,1.00000,3.50000,3.00000,4.06929,0.16265,False
173,"TIB - 0,57",61.00000,33,0.75000,44.00000,0.57000,1.00000,5.10000,4.60000,5.47344,0.07322,False
174,"TIB - 0,76",60.00000,33,0.75000,44.00000,0.76000,1.00000,7.30000,6.30000,6.68785,0.08386,False
175,"TIB - 0,38",42.60000,50,0.74627,67.00000,0.38000,1.00000,2.90000,3.00000,3.93833,0.35805,erro alto
176,"TIB - 0,57",40.00000,50,0.74627,67.00000,0.57000,1.00000,4.70000,5.20000,5.12729,0.09091,False
177,"TIB - 0,76",47.70000,50,0.74627,67.00000,0.76000,1.00000,6.00000,6.40000,6.85709,0.14285,False
178,"TIB - 0,38",59.30000,50,0.74627,67.00000,0.38000,1.00000,4.70000,4.40000,4.59920,0.02145,False
179,"TIB - 0,57",61.10000,50,0.74627,67.00000,0.57000,1.00000,6.10000,6.30000,6.25424,0.02529,False
180,"TIB - 0,76",57.40000,50,0.74627,67.00000,0.76000,1.00000,8.00000,8.20000,7.47901,0.06512,False
181,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.60000,2.80000,3.63882,0.39955,erro alto
182,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.90000,5.60000,4.83402,0.01346,False
183,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,6.40000,6.50000,6.49919,0.01550,False
184,"TIB - 0,38",61.20000,50,0.89286,56.00000,0.38000,1.00000,4.50000,4.80000,4.41111,0.01975,False
185,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.40000,7.00000,5.86941,0.08290,False
186,"TIB - 0,76",60.40000,50,0.89286,56.00000,0.76000,1.00000,9.20000,9.70000,7.23874,0.21318,erro alto
187,"TIB - 0,38",41.80000,50,0.74627,67.00000,0.38000,1.00000,3.90000,4.50000,3.90347,0.00089,False
188,"TIB - 0,57",40.90000,50,0.74627,67.00000,0.57000,1.00000,6.30000,6.60000,5.18107,0.17761,False
189,"TIB - 0,76",41.60000,50,0.74627,67.00000,0.76000,1.00000,7.30000,8.00000,6.43086,0.11906,False
190,"TIB - 0,38",61.10000,50,0.74627,67.00000,0.38000,1.00000,5.40000,6.10000,4.66415,0.13627,False
191,"TIB - 0,57",62.80000,50,0.74627,67.00000,0.57000,1.00000,6.90000,8.00000,6.33526,0.08185,False
192,"TIB - 0,76",60.00000,50,0.74627,67.00000,0.76000,1.00000,8.80000,9.70000,7.63603,0.13227,False
193,"TIB - 0,38",39.70000,37,0.74000,50.00000,0.38000,1.00000,2.50000,2.30000,3.47437,0.38975,erro alto
194,"TIB - 0,57",40.50000,37,0.74000,50.00000,0.57000,1.00000,3.50000,3.60000,4.70264,0.34361,erro alto
195,"TIB - 0,76",42.90000,37,0.74000,50.00000,0.76000,1.00000,5.70000,4.50000,5.94923,0.04372,False
196,"TIB - 0,38",59.00000,37,0.74000,50.00000,0.38000,1.00000,4.10000,4.00000,4.18382,0.02044,False
197,"TIB - 0,57",61.60000,37,0.74000,50.00000,0.57000,1.00000,5.10000,5.20000,5.72478,0.12251,False
198,"TIB - 0,76",60.00000,37,0.74000,50.00000,0.76000,1.00000,6.30000,6.10000,6.96292,0.10523,False
199,"TIB - 0,38",57.10000,50,0.89286,56.00000,0.38000,1.00000,4.40000,5.80000,4.26996,0.02955,False
200,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.90000,7.80000,5.86941,0.14936,False

In [128]:
#Gradient Boosting (erro > 25%)
from sklearn.ensemble import GradientBoostingRegressor

error_threshold = 0.25

gbr = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)
gbr.fit(X, y)

y_pred = gbr.predict(X)

percent_error = np.abs(y - y_pred) / np.abs(y)

removed_idx_gbr = percent_error[percent_error > error_threshold].index
kept_idx_gbr = percent_error[percent_error <= error_threshold].index

print("Gradient Boosting")
print(f"Amostras removidas (>25% erro): {len(removed_idx_gbr)}")
print(f"Amostras mantidas: {len(kept_idx_gbr)}")

display(df.loc[kept_idx_gbr])

Gradient Boosting
Amostras removidas (>25% erro): 10
Amostras mantidas: 281

,Tipo do concreto,fck (resistência) [MPa],l (comprimento) [mm],d (diâmetro [mm],l/d (fator de forma,Teor de fibra (%),N (ganchos),"fR,1 (N/mm²) (experimental)","fR,3 (N/mm²) (experimental)",Unnamed: 13,Unnamed: 14,Unnamed: 15
0,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.99000,3.32000,4.76991,0.04411,False
1,AM-0.8-EH1,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.44000,5.68000,8.02504,0.07863,False
2,AM-0.4-EH2,63.60000,60,0.89996,66.67000,0.40000,1.00000,5.35000,5.53000,4.92472,0.07949,False
3,AM-0.8-EH2,58.70000,60,0.89996,66.67000,0.80000,1.00000,7.94000,8.78000,7.83153,0.01366,False
4,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.49000,3.03000,4.76991,0.13116,False
5,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.37000,3.28000,4.76991,0.09151,False
6,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.67000,2.98000,4.76991,0.02139,False
7,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.22000,3.06000,4.76991,0.08622,False
8,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.74000,3.50000,4.76991,0.00631,False
9,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.46000,4.09000,4.76991,0.12639,False
10,AM-0.4-EH,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.93000,3.33000,4.76991,0.03247,False
11,AM-0.8-EH,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.46000,5.68000,8.02504,0.07574,False
12,"0.5FF320MPA, 2",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.12800,4.70400,3.52328,0.14649,False
13,"0.5FF320MPA, 3",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.10880,4.52160,3.52328,0.14250,False
14,"1.0FF320MPA, 1",22.00000,50,0.74627,67.00000,1.00000,1.00000,6.74880,7.32480,5.81758,0.13798,False
15,"1.0FF320MPA, 4",22.00000,50,0.74627,67.00000,1.00000,1.00000,5.78880,5.50080,5.81758,0.00497,False
16,"0.5FF330MPA, 2",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.01120,6.04800,4.77150,0.04783,False
17,"0.5FF330MPA, 3",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.49120,6.63360,4.77150,0.13106,False
18,"0.5FF330MPA, 4",42.00000,50,0.74627,67.00000,0.50000,1.00000,6.06720,7.49760,4.77150,0.21356,erro alto
19,"1.0FF330MPA, 1",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.07200,9.55200,7.87862,0.13155,False
20,"1.0FF330MPA, 2",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.83200,9.51360,7.87862,0.10795,False
21,"1.0FF330MPA, 3",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.64960,8.37120,7.87862,0.08914,False
22,"1.0FF330MPA, 4",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.23520,9.53280,7.87862,0.14689,False
23,"0.5FS720MPA, 1",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.11040,3.12000,3.54454,0.13958,False
24,"0.5FS720MPA, 2",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.75520,2.64000,3.54454,0.28649,erro alto
25,"0.5FS720MPA, 3",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.37920,3.40800,3.54454,0.04893,False
26,"0.5FS720MPA, 4",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.98560,2.89920,3.54454,0.18721,False
27,"1.0FS720MPA, 1",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.71200,5.12640,5.85268,0.02463,False
28,"1.0FS720MPA, 2",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.40480,5.10720,5.85268,0.08287,False
29,"1.0FS720MPA, 3",24.00000,33,0.55000,60.00000,1.00000,1.00000,6.01280,4.67840,5.85268,0.02663,False
30,"1.0FS720MPA, 4",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.79840,5.37600,5.85268,0.00936,False
31,"0.5FS730MPA, 1",43.00000,33,0.55000,60.00000,0.50000,1.00000,6.91200,6.94080,4.65948,0.32589,erro alto
32,"0.5FS730MPA, 2",43.00000,33,0.55000,60.00000,0.50000,1.00000,6.24960,6.34560,4.65948,0.25444,erro alto
33,"0.5FS730MPA, 3",43.00000,33,0.55000,60.00000,0.50000,1.00000,5.86560,6.60480,4.65948,0.20563,erro alto
34,"1.0FS730MPA, 1",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.50400,9.60000,7.85945,0.17304,False
35,"1.0FS730MPA, 2",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.55200,10.70400,7.85945,0.17719,False
36,"1.0FS730MPA, 3",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.21600,9.59040,7.85945,0.14719,False
37,"1.0FS730MPA, 4",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.42400,9.96480,7.85945,0.16602,False
38,"0.5FS3N20MPA, 2",22.00000,33,0.75000,44.00000,0.50000,1.00000,3.20640,3.06240,3.08579,0.03762,False
39,"0.5FS3N20MPA, 3",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.64960,2.62080,3.08579,0.16462,False
40,"0.5FS3N20MPA, 4",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.63040,2.74560,3.08579,0.17313,False
41,"0.5FS3N30MPA, 1",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.72480,4.65600,3.93783,0.05719,False
42,"0.5FS3N30MPA, 2",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.36960,4.60800,3.93783,0.16863,False
43,"0.5FS3N30MPA, 3",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.69600,5.36640,3.93783,0.06543,False
44,"0.5FS3N30MPA, 4",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.84960,3.99360,3.93783,0.02292,False
45,"1.0FS3N30MPA, 1",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.99040,3.34080,6.33480,0.05749,False
46,"1.0FS3N30MPA, 2",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.76000,3.76320,6.33480,0.09979,False
47,"1.0FS3N30MPA, 3",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.98400,3.91680,6.33480,0.05862,False
48,"1.0FS3N30MPA, 4",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.55200,6.79680,6.33480,0.14099,False
49,M32,38.60000,60,0.90000,66.66667,0.25000,1.00000,2.38000,2.76000,2.77321,0.16521,False
50,M34,37.30000,60,0.90000,66.66667,0.50000,1.00000,5.29000,7.00000,4.50608,0.14819,False
51,M36,36.00000,60,0.90000,66.66667,0.75000,1.00000,7.29000,8.04000,5.94259,0.18483,False
52,M38,41.10000,60,0.90000,66.66667,1.00000,1.00000,6.82000,9.51000,7.78672,0.14175,False
53,H32,46.10000,60,0.90000,66.66667,0.25000,1.00000,3.31000,3.78000,3.01404,0.08942,False
54,H34,46.70000,60,0.90000,66.66667,0.50000,1.00000,6.21000,7.54000,5.00700,0.19372,False
55,H36,48.00000,60,0.90000,66.66667,0.75000,1.00000,6.61000,8.22000,6.80099,0.02889,False
56,H38,48.50000,60,0.90000,66.66667,1.00000,1.00000,8.29000,9.76000,8.41542,0.01513,False
57,H34A,47.60000,60,0.75000,80.00000,0.50000,1.00000,6.23000,7.88000,5.35096,0.14110,False
58,H34S,45.40000,35,0.55000,63.63636,0.50000,1.00000,6.06000,5.16000,4.86919,0.19650,False
59,3D20,59.00000,60,0.75000,80.00000,0.25000,1.00000,2.26000,2.23000,3.58400,0.58584,erro alto
60,3D40,59.00000,60,0.75000,80.00000,0.50000,1.00000,3.79000,4.55000,5.91784,0.56144,erro alto
61,"3D-0,37",51.00000,60,0.90000,66.66667,0.37000,1.00000,5.53000,6.25000,4.19669,0.24110,erro alto
62,"3D-0,60",49.00000,60,0.90000,66.66667,0.60000,1.00000,6.37000,6.49000,5.84329,0.08269,False
63,"3D-1,0",51.00000,60,0.90000,66.66667,1.00000,1.00000,12.00000,13.31000,8.61615,0.28199,erro alto
64,"4D-0,37",52.00000,60,0.90000,66.66667,0.37000,1.50000,4.76000,5.95000,4.39790,0.07607,False
65,"ABD - 0,5",47.50000,35,0.53846,65.00000,0.50000,1.00000,3.40000,2.20000,5.00692,0.47262,erro alto
66,"ABD - 1,0",46.80000,35,0.53846,65.00000,1.00000,1.00000,5.10000,4.20000,8.20997,0.60980,erro alto
67,"ABD - 0,5",48.50000,60,0.92308,65.00000,0.50000,1.00000,5.60000,4.60000,5.05608,0.09713,False
69,"LEE - 0,37",49.90000,60,0.92308,65.00000,0.37000,1.00000,5.30000,6.30000,4.12097,0.22246,erro alto
70,"LEE - 0,60",49.30000,60,0.92308,65.00000,0.60000,1.00000,6.40000,6.50000,5.81345,0.09165,False
71,"LEE - 1,00",49.80000,60,0.92308,65.00000,1.00000,1.00000,12.00000,13.30000,8.45272,0.29561,erro alto
72,"GRI - 0,5",50.80000,50,0.74627,67.00000,0.50000,1.00000,3.70000,4.10000,5.21676,0.40994,erro alto
73,"GRI - 0,5",50.80000,50,0.74627,67.00000,0.50000,1.00000,3.40000,3.70000,5.21676,0.53434,erro alto
75,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,3.30000,4.40000,5.09968,0.54536,erro alto
76,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,3.40000,4.90000,5.09968,0.49991,erro alto
77,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.00000,5.20000,5.09968,0.27492,erro alto
78,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.20000,5.60000,5.09968,0.21421,erro alto
79,BEN - 1,66.20000,50,0.62500,80.00000,1.00000,1.00000,13.80000,11.60000,10.31362,0.25264,erro alto
80,BEN - 1,64.60000,50,0.62500,80.00000,1.00000,1.00000,11.80000,11.40000,10.19595,0.13594,False
81,BEN - 1,62.60000,50,0.62500,80.00000,1.00000,1.00000,8.00000,7.10000,10.04667,0.25583,erro alto
82,BEN - 2,62.70000,50,0.62500,80.00000,2.00000,1.00000,14.10000,15.40000,16.60132,0.17740,False
83,BEN - 2,60.80000,50,0.62500,80.00000,2.00000,1.00000,13.70000,14.30000,16.36345,0.19441,False
84,BEN - 2,64.20000,50,0.62500,80.00000,2.00000,1.00000,13.50000,13.00000,16.78642,0.24344,erro alto
85,"CUE - 0,38",24.80000,30,0.60000,50.00000,0.38000,1.00000,2.50000,2.40000,2.78638,0.11455,False
86,"CUE - 0,38",33.50000,50,1.00000,50.00000,0.38000,1.00000,2.60000,2.30000,3.20841,0.23400,erro alto
87,"CUE - 0,38",38.60000,30,0.60000,50.00000,0.38000,1.00000,3.30000,2.70000,3.42888,0.03906,False
88,"CUE - 0,65",61.10000,30,0.62500,48.00000,0.64583,1.00000,2.90000,2.80000,6.16248,1.12499,erro alto
89,"CUE - 0,64",58.30000,30,0.37975,79.00000,0.63924,1.00000,6.50000,5.40000,7.00169,0.07718,False
90,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
91,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
92,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
93,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
94,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
95,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
96,"CUE - 0,25",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
97,"CUE - 0,25",55.00000,50,1.00000,50.00000,0.25000,1.00000,2.50000,2.50000,2.99026,0.19611,False
98,"CUE - 0,38",40.70000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.51514,0.67388,erro alto
99,"CUE - 0,38",45.10000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.68852,0.75644,erro alto
100,"CUE - 0,38",45.10000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.68852,0.75644,erro alto
101,"CUE - 0,38",40.70000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.51514,0.67388,erro alto
102,"CUE - 0,38",41.60000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.55139,0.69114,erro alto
103,"CUE - 0,38",41.60000,50,1.00000,50.00000,0.38000,1.00000,2.10000,1.90000,3.55139,0.69114,erro alto
104,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
105,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
106,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
107,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
108,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
109,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
110,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
111,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
112,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
113,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
114,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
115,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
116,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
117,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
118,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
119,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
120,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
121,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
122,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
123,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
124,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
125,"POH - 0,38",45.90000,60,0.75000,80.00000,0.38000,1.00000,4.00000,2.60000,4.31313,0.07828,False
126,"POH - 0,44",34.70000,60,0.75000,80.00000,0.44000,1.00000,3.00000,3.00000,4.20612,0.40204,erro alto
128,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.60000,3.50000,4.26324,0.18423,False
129,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.80000,3.70000,4.26324,0.12190,False
130,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.90000,3.90000,4.26324,0.09314,False
131,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,4.90000,3.10000,5.29172,0.07994,False
132,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.10000,3.80000,5.29172,0.03759,False
133,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.40000,4.30000,5.29172,0.02005,False
134,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.30000,6.80000,6.50244,0.03213,False
135,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.90000,7.50000,6.50244,0.05762,False
136,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,7.50000,8.60000,6.50244,0.13301,False
137,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,8.80000,6.70000,9.05476,0.02895,False
138,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,9.90000,7.50000,9.05476,0.08538,False
139,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,11.00000,8.60000,9.05476,0.17684,False
140,"BAR - 0,13",31.80000,60,0.75000,80.00000,0.13000,1.00000,1.70000,1.70000,1.67111,0.01699,False
141,"BAR - 0,26",31.80000,60,0.75000,80.00000,0.26000,1.00000,2.60000,2.20000,2.75931,0.06127,False
142,"BAR - 0,39",31.80000,60,0.75000,80.00000,0.39000,1.00000,3.50000,3.70000,3.70001,0.05714,False
143,"BAR - 0,19",31.80000,60,0.92308,65.00000,0.19000,1.00000,2.60000,3.40000,2.05974,0.20779,erro alto
144,"BAR - 0,32",31.80000,60,0.92308,65.00000,0.32000,1.00000,3.90000,3.90000,3.00338,0.22990,erro alto
145,"BAR - 0,45",31.80000,60,0.92308,65.00000,0.45000,1.00000,4.10000,2.40000,3.84356,0.06255,False
146,"BAR - 0,58",31.80000,60,0.92308,65.00000,0.58000,1.00000,5.90000,5.80000,4.61822,0.21725,erro alto
148,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,3.80000,2.50000,4.93435,0.29851,erro alto
149,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.60000,2.60000,4.93435,0.07268,False
150,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.70000,2.70000,4.93435,0.04986,False
151,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.80000,2.80000,4.93435,0.02799,False
152,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,2.90000,4.93435,0.00701,False
153,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,3.10000,4.93435,0.00701,False
154,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,5.30000,4.10000,4.93435,0.06899,False
155,"BRG - 0,27",38.90000,60,0.75000,80.00000,0.27000,1.00000,2.20000,2.60000,3.11679,0.41672,erro alto
157,"BRG - 0,27",38.90000,60,0.75000,80.00000,0.27000,1.00000,3.10000,3.70000,3.11679,0.00541,False
158,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,4.50000,5.80000,5.04037,0.12008,False
159,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,3.90000,5.10000,5.04037,0.29240,erro alto
161,"MON - 1,00",46.90000,35,0.54688,64.00000,1.00000,1.00000,8.40000,7.10000,8.17811,0.02641,False
162,"MON - 1,25",56.10000,35,0.54688,64.00000,1.25000,1.00000,8.60000,8.10000,10.45324,0.21549,erro alto
163,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.70000,2.80000,3.63882,0.34771,erro alto
164,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.60000,5.20000,4.83402,0.05087,False
165,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,5.40000,6.00000,6.49919,0.20355,erro alto
166,"TIB - 0,38",60.20000,50,0.89286,56.00000,0.38000,1.00000,4.00000,4.20000,4.37716,0.09429,False
167,"TIB - 0,57",57.80000,50,0.89286,56.00000,0.57000,1.00000,6.10000,6.70000,5.75848,0.05599,False
168,"TIB - 0,76",61.90000,50,0.89286,56.00000,0.76000,1.00000,8.10000,8.30000,7.32251,0.09599,False
169,"TIB - 0,38",43.00000,33,0.75000,44.00000,0.38000,1.00000,2.40000,2.20000,3.46446,0.44352,erro alto
170,"TIB - 0,57",41.80000,33,0.75000,44.00000,0.57000,1.00000,3.80000,3.60000,4.58429,0.20639,erro alto
171,"TIB - 0,76",40.90000,33,0.75000,44.00000,0.76000,1.00000,4.60000,4.50000,5.58769,0.21471,erro alto
172,"TIB - 0,38",60.60000,33,0.75000,44.00000,0.38000,1.00000,3.50000,3.00000,4.06929,0.16265,False
173,"TIB - 0,57",61.00000,33,0.75000,44.00000,0.57000,1.00000,5.10000,4.60000,5.47344,0.07322,False
174,"TIB - 0,76",60.00000,33,0.75000,44.00000,0.76000,1.00000,7.30000,6.30000,6.68785,0.08386,False
176,"TIB - 0,57",40.00000,50,0.74627,67.00000,0.57000,1.00000,4.70000,5.20000,5.12729,0.09091,False
177,"TIB - 0,76",47.70000,50,0.74627,67.00000,0.76000,1.00000,6.00000,6.40000,6.85709,0.14285,False
178,"TIB - 0,38",59.30000,50,0.74627,67.00000,0.38000,1.00000,4.70000,4.40000,4.59920,0.02145,False
179,"TIB - 0,57",61.10000,50,0.74627,67.00000,0.57000,1.00000,6.10000,6.30000,6.25424,0.02529,False
180,"TIB - 0,76",57.40000,50,0.74627,67.00000,0.76000,1.00000,8.00000,8.20000,7.47901,0.06512,False
181,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.60000,2.80000,3.63882,0.39955,erro alto
182,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.90000,5.60000,4.83402,0.01346,False
183,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,6.40000,6.50000,6.49919,0.01550,False
184,"TIB - 0,38",61.20000,50,0.89286,56.00000,0.38000,1.00000,4.50000,4.80000,4.41111,0.01975,False
185,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.40000,7.00000,5.86941,0.08290,False
186,"TIB - 0,76",60.40000,50,0.89286,56.00000,0.76000,1.00000,9.20000,9.70000,7.23874,0.21318,erro alto
187,"TIB - 0,38",41.80000,50,0.74627,67.00000,0.38000,1.00000,3.90000,4.50000,3.90347,0.00089,False
188,"TIB - 0,57",40.90000,50,0.74627,67.00000,0.57000,1.00000,6.30000,6.60000,5.18107,0.17761,False
189,"TIB - 0,76",41.60000,50,0.74627,67.00000,0.76000,1.00000,7.30000,8.00000,6.43086,0.11906,False
190,"TIB - 0,38",61.10000,50,0.74627,67.00000,0.38000,1.00000,5.40000,6.10000,4.66415,0.13627,False
191,"TIB - 0,57",62.80000,50,0.74627,67.00000,0.57000,1.00000,6.90000,8.00000,6.33526,0.08185,False
192,"TIB - 0,76",60.00000,50,0.74627,67.00000,0.76000,1.00000,8.80000,9.70000,7.63603,0.13227,False
193,"TIB - 0,38",39.70000,37,0.74000,50.00000,0.38000,1.00000,2.50000,2.30000,3.47437,0.38975,erro alto
194,"TIB - 0,57",40.50000,37,0.74000,50.00000,0.57000,1.00000,3.50000,3.60000,4.70264,0.34361,erro alto
195,"TIB - 0,76",42.90000,37,0.74000,50.00000,0.76000,1.00000,5.70000,4.50000,5.94923,0.04372,False
196,"TIB - 0,38",59.00000,37,0.74000,50.00000,0.38000,1.00000,4.10000,4.00000,4.18382,0.02044,False
197,"TIB - 0,57",61.60000,37,0.74000,50.00000,0.57000,1.00000,5.10000,5.20000,5.72478,0.12251,False
198,"TIB - 0,76",60.00000,37,0.74000,50.00000,0.76000,1.00000,6.30000,6.10000,6.96292,0.10523,False
199,"TIB - 0,38",57.10000,50,0.89286,56.00000,0.38000,1.00000,4.40000,5.80000,4.26996,0.02955,False
200,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.90000,7.80000,5.86941,0.14936,False
201,"TIB - 0,76",60.90000,50,0.89286,56.00000,0.76000,1.00000,10.70000,9.50000,7.26679,0.32086,erro alto
202,"TIB - 0,38",56.60000,50,0.74627,67.00000,0.38000,1.00000,5.70000,6.60000,4.49977,0.21057,erro alto

In [129]:
common_kept = (
    set(kept_idx_lr)
    & set(kept_idx_rf)
    & set(kept_idx_gbr)
)

print(f"Amostras mantidas pelos 3 modelos (erro ≤ 25%): {len(common_kept)}")
display(df.loc[list(common_kept)])

Amostras mantidas pelos 3 modelos (erro ≤ 25%): 232

,Tipo do concreto,fck (resistência) [MPa],l (comprimento) [mm],d (diâmetro [mm],l/d (fator de forma,Teor de fibra (%),N (ganchos),"fR,1 (N/mm²) (experimental)","fR,3 (N/mm²) (experimental)",Unnamed: 13,Unnamed: 14,Unnamed: 15
0,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.99000,3.32000,4.76991,0.04411,False
1,AM-0.8-EH1,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.44000,5.68000,8.02504,0.07863,False
2,AM-0.4-EH2,63.60000,60,0.89996,66.67000,0.40000,1.00000,5.35000,5.53000,4.92472,0.07949,False
3,AM-0.8-EH2,58.70000,60,0.89996,66.67000,0.80000,1.00000,7.94000,8.78000,7.83153,0.01366,False
4,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.49000,3.03000,4.76991,0.13116,False
5,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.37000,3.28000,4.76991,0.09151,False
6,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.67000,2.98000,4.76991,0.02139,False
7,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.22000,3.06000,4.76991,0.08622,False
8,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.74000,3.50000,4.76991,0.00631,False
9,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.46000,4.09000,4.76991,0.12639,False
10,AM-0.4-EH,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.93000,3.33000,4.76991,0.03247,False
11,AM-0.8-EH,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.46000,5.68000,8.02504,0.07574,False
12,"0.5FF320MPA, 2",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.12800,4.70400,3.52328,0.14649,False
13,"0.5FF320MPA, 3",22.00000,50,0.74627,67.00000,0.50000,1.00000,4.10880,4.52160,3.52328,0.14250,False
14,"1.0FF320MPA, 1",22.00000,50,0.74627,67.00000,1.00000,1.00000,6.74880,7.32480,5.81758,0.13798,False
15,"1.0FF320MPA, 4",22.00000,50,0.74627,67.00000,1.00000,1.00000,5.78880,5.50080,5.81758,0.00497,False
16,"0.5FF330MPA, 2",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.01120,6.04800,4.77150,0.04783,False
17,"0.5FF330MPA, 3",42.00000,50,0.74627,67.00000,0.50000,1.00000,5.49120,6.63360,4.77150,0.13106,False
18,"0.5FF330MPA, 4",42.00000,50,0.74627,67.00000,0.50000,1.00000,6.06720,7.49760,4.77150,0.21356,erro alto
19,"1.0FF330MPA, 1",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.07200,9.55200,7.87862,0.13155,False
20,"1.0FF330MPA, 2",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.83200,9.51360,7.87862,0.10795,False
21,"1.0FF330MPA, 3",42.00000,50,0.74627,67.00000,1.00000,1.00000,8.64960,8.37120,7.87862,0.08914,False
22,"1.0FF330MPA, 4",42.00000,50,0.74627,67.00000,1.00000,1.00000,9.23520,9.53280,7.87862,0.14689,False
23,"0.5FS720MPA, 1",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.11040,3.12000,3.54454,0.13958,False
24,"0.5FS720MPA, 2",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.75520,2.64000,3.54454,0.28649,erro alto
25,"0.5FS720MPA, 3",24.00000,33,0.55000,60.00000,0.50000,1.00000,3.37920,3.40800,3.54454,0.04893,False
26,"0.5FS720MPA, 4",24.00000,33,0.55000,60.00000,0.50000,1.00000,2.98560,2.89920,3.54454,0.18721,False
27,"1.0FS720MPA, 1",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.71200,5.12640,5.85268,0.02463,False
28,"1.0FS720MPA, 2",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.40480,5.10720,5.85268,0.08287,False
29,"1.0FS720MPA, 3",24.00000,33,0.55000,60.00000,1.00000,1.00000,6.01280,4.67840,5.85268,0.02663,False
30,"1.0FS720MPA, 4",24.00000,33,0.55000,60.00000,1.00000,1.00000,5.79840,5.37600,5.85268,0.00936,False
34,"1.0FS730MPA, 1",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.50400,9.60000,7.85945,0.17304,False
35,"1.0FS730MPA, 2",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.55200,10.70400,7.85945,0.17719,False
36,"1.0FS730MPA, 3",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.21600,9.59040,7.85945,0.14719,False
37,"1.0FS730MPA, 4",45.00000,33,0.55000,60.00000,1.00000,1.00000,9.42400,9.96480,7.85945,0.16602,False
38,"0.5FS3N20MPA, 2",22.00000,33,0.75000,44.00000,0.50000,1.00000,3.20640,3.06240,3.08579,0.03762,False
39,"0.5FS3N20MPA, 3",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.64960,2.62080,3.08579,0.16462,False
40,"0.5FS3N20MPA, 4",22.00000,33,0.75000,44.00000,0.50000,1.00000,2.63040,2.74560,3.08579,0.17313,False
41,"0.5FS3N30MPA, 1",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.72480,4.65600,3.93783,0.05719,False
42,"0.5FS3N30MPA, 2",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.36960,4.60800,3.93783,0.16863,False
43,"0.5FS3N30MPA, 3",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.69600,5.36640,3.93783,0.06543,False
44,"0.5FS3N30MPA, 4",37.00000,33,0.75000,44.00000,0.50000,1.00000,3.84960,3.99360,3.93783,0.02292,False
45,"1.0FS3N30MPA, 1",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.99040,3.34080,6.33480,0.05749,False
46,"1.0FS3N30MPA, 2",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.76000,3.76320,6.33480,0.09979,False
47,"1.0FS3N30MPA, 3",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.98400,3.91680,6.33480,0.05862,False
48,"1.0FS3N30MPA, 4",35.00000,33,0.75000,44.00000,1.00000,1.00000,5.55200,6.79680,6.33480,0.14099,False
49,M32,38.60000,60,0.90000,66.66667,0.25000,1.00000,2.38000,2.76000,2.77321,0.16521,False
50,M34,37.30000,60,0.90000,66.66667,0.50000,1.00000,5.29000,7.00000,4.50608,0.14819,False
51,M36,36.00000,60,0.90000,66.66667,0.75000,1.00000,7.29000,8.04000,5.94259,0.18483,False
52,M38,41.10000,60,0.90000,66.66667,1.00000,1.00000,6.82000,9.51000,7.78672,0.14175,False
53,H32,46.10000,60,0.90000,66.66667,0.25000,1.00000,3.31000,3.78000,3.01404,0.08942,False
54,H34,46.70000,60,0.90000,66.66667,0.50000,1.00000,6.21000,7.54000,5.00700,0.19372,False
55,H36,48.00000,60,0.90000,66.66667,0.75000,1.00000,6.61000,8.22000,6.80099,0.02889,False
56,H38,48.50000,60,0.90000,66.66667,1.00000,1.00000,8.29000,9.76000,8.41542,0.01513,False
57,H34A,47.60000,60,0.75000,80.00000,0.50000,1.00000,6.23000,7.88000,5.35096,0.14110,False
58,H34S,45.40000,35,0.55000,63.63636,0.50000,1.00000,6.06000,5.16000,4.86919,0.19650,False
61,"3D-0,37",51.00000,60,0.90000,66.66667,0.37000,1.00000,5.53000,6.25000,4.19669,0.24110,erro alto
62,"3D-0,60",49.00000,60,0.90000,66.66667,0.60000,1.00000,6.37000,6.49000,5.84329,0.08269,False
64,"4D-0,37",52.00000,60,0.90000,66.66667,0.37000,1.50000,4.76000,5.95000,4.39790,0.07607,False
67,"ABD - 0,5",48.50000,60,0.92308,65.00000,0.50000,1.00000,5.60000,4.60000,5.05608,0.09713,False
69,"LEE - 0,37",49.90000,60,0.92308,65.00000,0.37000,1.00000,5.30000,6.30000,4.12097,0.22246,erro alto
70,"LEE - 0,60",49.30000,60,0.92308,65.00000,0.60000,1.00000,6.40000,6.50000,5.81345,0.09165,False
77,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.00000,5.20000,5.09968,0.27492,erro alto
78,"GRI - 0,5",48.40000,50,0.74627,67.00000,0.50000,1.00000,4.20000,5.60000,5.09968,0.21421,erro alto
80,BEN - 1,64.60000,50,0.62500,80.00000,1.00000,1.00000,11.80000,11.40000,10.19595,0.13594,False
81,BEN - 1,62.60000,50,0.62500,80.00000,1.00000,1.00000,8.00000,7.10000,10.04667,0.25583,erro alto
82,BEN - 2,62.70000,50,0.62500,80.00000,2.00000,1.00000,14.10000,15.40000,16.60132,0.17740,False
83,BEN - 2,60.80000,50,0.62500,80.00000,2.00000,1.00000,13.70000,14.30000,16.36345,0.19441,False
84,BEN - 2,64.20000,50,0.62500,80.00000,2.00000,1.00000,13.50000,13.00000,16.78642,0.24344,erro alto
85,"CUE - 0,38",24.80000,30,0.60000,50.00000,0.38000,1.00000,2.50000,2.40000,2.78638,0.11455,False
86,"CUE - 0,38",33.50000,50,1.00000,50.00000,0.38000,1.00000,2.60000,2.30000,3.20841,0.23400,erro alto
87,"CUE - 0,38",38.60000,30,0.60000,50.00000,0.38000,1.00000,3.30000,2.70000,3.42888,0.03906,False
89,"CUE - 0,64",58.30000,30,0.37975,79.00000,0.63924,1.00000,6.50000,5.40000,7.00169,0.07718,False
90,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
91,"CUE - 0,15",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
92,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
93,"CUE - 0,31",20.60000,50,1.00000,50.00000,0.50000,1.00000,3.10000,2.90000,3.11515,0.00489,False
94,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
95,"CUE - 0,76",19.20000,50,1.00000,50.00000,0.76000,1.00000,4.40000,4.60000,4.08044,0.07263,False
96,"CUE - 0,25",24.40000,50,1.00000,50.00000,0.25000,1.00000,1.50000,1.50000,2.04251,0.36168,erro alto
104,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
105,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
106,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
107,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
108,"CUE - 0,67",32.10000,50,1.00000,50.00000,0.67000,1.00000,5.40000,5.00000,4.74008,0.12221,False
109,"CUE - 1,00",33.10000,50,1.00000,50.00000,1.00000,1.00000,6.00000,6.00000,6.42494,0.07082,False
110,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
111,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
112,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
113,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
114,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
115,"CUE - 0,33",38.00000,50,1.00000,50.00000,0.33000,1.00000,3.00000,3.00000,3.07350,0.02450,False
116,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
117,"CUE - 0,44",36.90000,50,1.00000,50.00000,0.44000,1.00000,3.50000,3.60000,3.73287,0.06654,False
118,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
119,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
120,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
121,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
122,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
123,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
124,"CUE - 0,33",35.30000,50,1.00000,50.00000,0.33000,1.00000,2.20000,2.20000,2.96907,0.34958,erro alto
125,"POH - 0,38",45.90000,60,0.75000,80.00000,0.38000,1.00000,4.00000,2.60000,4.31313,0.07828,False
130,"BAR - 0,33",64.00000,60,0.92308,65.00000,0.33000,1.00000,3.90000,3.90000,4.26324,0.09314,False
131,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,4.90000,3.10000,5.29172,0.07994,False
132,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.10000,3.80000,5.29172,0.03759,False
133,"BAR - 0,47",58.80000,60,0.92308,65.00000,0.47000,1.00000,5.40000,4.30000,5.29172,0.02005,False
134,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.30000,6.80000,6.50244,0.03213,False
135,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,6.90000,7.50000,6.50244,0.05762,False
136,"BAR - 0,67",52.80000,60,0.92308,65.00000,0.67000,1.00000,7.50000,8.60000,6.50244,0.13301,False
137,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,8.80000,6.70000,9.05476,0.02895,False
138,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,9.90000,7.50000,9.05476,0.08538,False
139,"BAR - 0,93",64.50000,60,0.92308,65.00000,0.93000,1.00000,11.00000,8.60000,9.05476,0.17684,False
140,"BAR - 0,13",31.80000,60,0.75000,80.00000,0.13000,1.00000,1.70000,1.70000,1.67111,0.01699,False
141,"BAR - 0,26",31.80000,60,0.75000,80.00000,0.26000,1.00000,2.60000,2.20000,2.75931,0.06127,False
142,"BAR - 0,39",31.80000,60,0.75000,80.00000,0.39000,1.00000,3.50000,3.70000,3.70001,0.05714,False
145,"BAR - 0,45",31.80000,60,0.92308,65.00000,0.45000,1.00000,4.10000,2.40000,3.84356,0.06255,False
149,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.60000,2.60000,4.93435,0.07268,False
150,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.70000,2.70000,4.93435,0.04986,False
151,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.80000,2.80000,4.93435,0.02799,False
152,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,2.90000,4.93435,0.00701,False
153,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,4.90000,3.10000,4.93435,0.00701,False
154,"PER - 0,4",56.50000,60,0.75000,80.00000,0.40000,1.00000,5.30000,4.10000,4.93435,0.06899,False
158,"BRG - 0,53",38.30000,60,0.75000,80.00000,0.53000,1.00000,4.50000,5.80000,5.04037,0.12008,False
161,"MON - 1,00",46.90000,35,0.54688,64.00000,1.00000,1.00000,8.40000,7.10000,8.17811,0.02641,False
162,"MON - 1,25",56.10000,35,0.54688,64.00000,1.25000,1.00000,8.60000,8.10000,10.45324,0.21549,erro alto
163,"TIB - 0,38",40.60000,50,0.89286,56.00000,0.38000,1.00000,2.70000,2.80000,3.63882,0.34771,erro alto
164,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.60000,5.20000,4.83402,0.05087,False
165,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,5.40000,6.00000,6.49919,0.20355,erro alto
166,"TIB - 0,38",60.20000,50,0.89286,56.00000,0.38000,1.00000,4.00000,4.20000,4.37716,0.09429,False
167,"TIB - 0,57",57.80000,50,0.89286,56.00000,0.57000,1.00000,6.10000,6.70000,5.75848,0.05599,False
168,"TIB - 0,76",61.90000,50,0.89286,56.00000,0.76000,1.00000,8.10000,8.30000,7.32251,0.09599,False
169,"TIB - 0,38",43.00000,33,0.75000,44.00000,0.38000,1.00000,2.40000,2.20000,3.46446,0.44352,erro alto
170,"TIB - 0,57",41.80000,33,0.75000,44.00000,0.57000,1.00000,3.80000,3.60000,4.58429,0.20639,erro alto
171,"TIB - 0,76",40.90000,33,0.75000,44.00000,0.76000,1.00000,4.60000,4.50000,5.58769,0.21471,erro alto
172,"TIB - 0,38",60.60000,33,0.75000,44.00000,0.38000,1.00000,3.50000,3.00000,4.06929,0.16265,False
173,"TIB - 0,57",61.00000,33,0.75000,44.00000,0.57000,1.00000,5.10000,4.60000,5.47344,0.07322,False
174,"TIB - 0,76",60.00000,33,0.75000,44.00000,0.76000,1.00000,7.30000,6.30000,6.68785,0.08386,False
176,"TIB - 0,57",40.00000,50,0.74627,67.00000,0.57000,1.00000,4.70000,5.20000,5.12729,0.09091,False
177,"TIB - 0,76",47.70000,50,0.74627,67.00000,0.76000,1.00000,6.00000,6.40000,6.85709,0.14285,False
178,"TIB - 0,38",59.30000,50,0.74627,67.00000,0.38000,1.00000,4.70000,4.40000,4.59920,0.02145,False
179,"TIB - 0,57",61.10000,50,0.74627,67.00000,0.57000,1.00000,6.10000,6.30000,6.25424,0.02529,False
180,"TIB - 0,76",57.40000,50,0.74627,67.00000,0.76000,1.00000,8.00000,8.20000,7.47901,0.06512,False
182,"TIB - 0,57",39.80000,50,0.89286,56.00000,0.57000,1.00000,4.90000,5.60000,4.83402,0.01346,False
183,"TIB - 0,76",48.00000,50,0.89286,56.00000,0.76000,1.00000,6.40000,6.50000,6.49919,0.01550,False
184,"TIB - 0,38",61.20000,50,0.89286,56.00000,0.38000,1.00000,4.50000,4.80000,4.41111,0.01975,False
185,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.40000,7.00000,5.86941,0.08290,False
186,"TIB - 0,76",60.40000,50,0.89286,56.00000,0.76000,1.00000,9.20000,9.70000,7.23874,0.21318,erro alto
187,"TIB - 0,38",41.80000,50,0.74627,67.00000,0.38000,1.00000,3.90000,4.50000,3.90347,0.00089,False
188,"TIB - 0,57",40.90000,50,0.74627,67.00000,0.57000,1.00000,6.30000,6.60000,5.18107,0.17761,False
189,"TIB - 0,76",41.60000,50,0.74627,67.00000,0.76000,1.00000,7.30000,8.00000,6.43086,0.11906,False
190,"TIB - 0,38",61.10000,50,0.74627,67.00000,0.38000,1.00000,5.40000,6.10000,4.66415,0.13627,False
191,"TIB - 0,57",62.80000,50,0.74627,67.00000,0.57000,1.00000,6.90000,8.00000,6.33526,0.08185,False
192,"TIB - 0,76",60.00000,50,0.74627,67.00000,0.76000,1.00000,8.80000,9.70000,7.63603,0.13227,False
193,"TIB - 0,38",39.70000,37,0.74000,50.00000,0.38000,1.00000,2.50000,2.30000,3.47437,0.38975,erro alto
194,"TIB - 0,57",40.50000,37,0.74000,50.00000,0.57000,1.00000,3.50000,3.60000,4.70264,0.34361,erro alto
195,"TIB - 0,76",42.90000,37,0.74000,50.00000,0.76000,1.00000,5.70000,4.50000,5.94923,0.04372,False
196,"TIB - 0,38",59.00000,37,0.74000,50.00000,0.38000,1.00000,4.10000,4.00000,4.18382,0.02044,False
197,"TIB - 0,57",61.60000,37,0.74000,50.00000,0.57000,1.00000,5.10000,5.20000,5.72478,0.12251,False
198,"TIB - 0,76",60.00000,37,0.74000,50.00000,0.76000,1.00000,6.30000,6.10000,6.96292,0.10523,False
199,"TIB - 0,38",57.10000,50,0.89286,56.00000,0.38000,1.00000,4.40000,5.80000,4.26996,0.02955,False
200,"TIB - 0,57",60.20000,50,0.89286,56.00000,0.57000,1.00000,6.90000,7.80000,5.86941,0.14936,False
202,"TIB - 0,38",56.60000,50,0.74627,67.00000,0.38000,1.00000,5.70000,6.60000,4.49977,0.21057,erro alto
203,"TIB - 0,57",57.40000,50,0.74627,67.00000,0.57000,1.00000,7.80000,9.40000,6.07367,0.22132,erro alto
204,"TIB - 0,76",59.60000,50,0.74627,67.00000,0.76000,1.00000,9.10000,11.00000,7.61211,0.16350,False
207,"TIB - 0,38",32.30000,50,1.00000,50.00000,0.38000,1.00000,2.10000,2.10000,3.15398,0.50190,erro alto
209,"TIB - 0,38",34.80000,44,0.97778,45.00000,0.38000,1.00000,2.40000,1.60000,3.15949,0.31645,erro alto
210,"TIB - 0,50",70.60000,30,0.37500,80.00000,0.50000,1.00000,7.30000,7.80000,6.43759,0.11814,False
211,"TIB - 1,00",71.80000,60,0.75000,80.00000,1.00000,1.00000,12.40000,11.80000,10.71399,0.13597,False
213,"TIB - 1,00",24.50000,30,0.62500,48.00000,1.00000,1.00000,5.80000,4.40000,5.50806,0.05033,False
214,"TIB - 0,50",39.30000,30,0.62500,48.00000,0.50000,1.00000,4.10000,3.40000,4.16346,0.01548,False
215,"TIB - 1,00",26.40000,30,0.62500,48.00000,1.00000,1.00000,5.40000,4.40000,5.70443,0.05638,False
216,"TIB - 1,00",33.70000,35,0.54688,64.00000,1.00000,1.00000,6.90000,6.20000,7.00376,0.01504,False
220,"TIB - 1,00",37.20000,35,0.54688,64.00000,1.00000,1.00000,9.50000,8.10000,7.33597,0.22779,erro alto
221,"TIB - 0,50",39.40000,35,0.54688,64.00000,0.50000,1.00000,5.40000,5.40000,4.56421,0.15478,False
222,"TIB - 1,00",44.50000,35,0.54688,64.00000,1.00000,1.00000,10.50000,9.20000,7.97910,0.24009,erro alto
223,"TIB - 0,50",37.60000,35,0.54688,64.00000,0.50000,1.00000,4.80000,5.20000,4.46520,0.06975,False
224,"TIB - 1,00",35.40000,35,0.54688,64.00000,1.00000,1.00000,6.80000,5.90000,7.16730,0.05401,False
225,"TIB - 0,50",41.00000,35,0.54688,64.00000,0.50000,1.00000,4.60000,4.80000,4.65022,0.01092,False
226,"TIB - 1,00",36.20000,35,0.54688,64.00000,1.00000,1.00000,7.40000,6.90000,7.24282,0.02124,False
229,"TIB - 1,00",45.10000,35,0.54688,64.00000,1.00000,1.00000,7.60000,7.00000,8.02938,0.05650,False
231,"TIB - 1,00",48.90000,80,0.80000,100.00000,1.00000,1.00000,8.30000,9.90000,9.59998,0.15662,False
232,M42,38.90000,60,0.90000,66.66667,0.25000,1.50000,3.26000,4.26000,2.89029,0.11341,False
233,M44,39.70000,60,0.90000,66.66667,0.50000,1.50000,4.89000,6.47000,4.81818,0.01469,False
234,M46,38.10000,60,0.90000,66.66667,0.75000,1.50000,6.16000,7.21000,6.33733,0.02879,False
235,M48,39.70000,60,0.90000,66.66667,1.00000,1.50000,9.08000,8.94000,7.95570,0.12382,False
236,M52,41.90000,60,0.90000,66.66667,0.25000,2.00000,3.32000,5.68000,3.14788,0.05184,False
237,M54,42.50000,60,0.90000,66.66667,0.50000,2.00000,5.42000,7.60000,5.23250,0.03459,False
238,M56,40.40000,60,0.90000,66.66667,0.75000,2.00000,6.20000,8.25000,6.85156,0.10509,False
239,M58,39.70000,60,0.90000,66.66667,1.00000,2.00000,9.35000,12.20000,8.36802,0.10502,False
240,L54,28.10000,60,0.90000,66.66667,0.50000,2.00000,4.62000,6.57000,4.30961,0.06718,False
241,H54,56.10000,60,0.90000,66.66667,0.50000,2.00000,5.51000,8.61000,5.96017,0.08170,False
242,"LEE - 0,37",49.80000,60,0.92308,65.00000,0.37000,1.50000,4.80000,6.00000,4.27537,0.10930,False
243,"LEE - 0,60",51.40000,60,0.92308,65.00000,0.60000,1.50000,6.20000,7.50000,6.15620,0.00706,False
244,"LEE - 1,00",51.70000,60,0.92308,65.00000,1.00000,1.50000,11.30000,13.60000,8.93317,0.20945,erro alto
245,"LEE - 0,37",48.00000,60,0.92308,65.00000,0.37000,2.00000,4.50000,7.50000,4.41997,0.01778,False
246,"LEE - 0,60",52.30000,60,0.92308,65.00000,0.60000,2.00000,5.60000,9.70000,6.52819,0.16575,False
247,"LEE - 1,00",49.80000,60,0.92308,65.00000,1.00000,2.00000,10.40000,12.00000,9.23259,0.11225,False

## Retreinando os modelos só com os pontos “bons”

## Reavaliando as métricas

## Extraindo equações lineares aproximadas

## Comparando modelos ML × equações

## Repetindo tudo para a DNN

In [131]:
# Criar o DataFrame apenas com as amostras mantidas pelos 3 modelos
df_common = df.loc[list(common_kept)].copy()

print("Shape do dataset consensual:", df_common.shape)
display(df_common.head())

Shape do dataset consensual: (232, 12)

,Tipo do concreto,fck (resistência) [MPa],l (comprimento) [mm],d (diâmetro [mm],l/d (fator de forma,Teor de fibra (%),N (ganchos),"fR,1 (N/mm²) (experimental)","fR,3 (N/mm²) (experimental)",Unnamed: 13,Unnamed: 14,Unnamed: 15
0,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,4.99000,3.32000,4.76991,0.04411,False
1,AM-0.8-EH1,63.80000,35,0.54997,63.64000,0.80000,1.00000,7.44000,5.68000,8.02504,0.07863,False
2,AM-0.4-EH2,63.60000,60,0.89996,66.67000,0.40000,1.00000,5.35000,5.53000,4.92472,0.07949,False
3,AM-0.8-EH2,58.70000,60,0.89996,66.67000,0.80000,1.00000,7.94000,8.78000,7.83153,0.01366,False
4,AM-0.4-EH1,61.30000,35,0.54997,63.64000,0.40000,1.00000,5.49000,3.03000,4.76991,0.13116,False

In [ ]:
#Definir X e y 
X_common = df_common[[
    'fck (resistência)            [MPa]',
    'l (comprimento)            [mm]',
    'd (diâmetro            [mm]',
    'l/d      (fator de forma             ',
    'Teor de fibra (%)',
    'N (ganchos)'
]]

y_fr1_common = df_common['fR,1 (N/mm²)      (experimental)']
y_fr3_common = df_common['fR,3 (N/mm²)      (experimental)']

In [ ]:
#Split único (usado por TODOS os modelos)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_fr1, y_test_fr1 = train_test_split(
    X_common, y_fr1_common, test_size=0.2, random_state=42
)

_, _, y_train_fr3, y_test_fr3 = train_test_split(
    X_common, y_fr3_common, test_size=0.2, random_state=42
)

In [135]:
#Função padrão de avaliação (evita repetir código)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(model, X_test, y_test, name="Modelo"):
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    print(f" {name}")
    print(f"MAE  = {mae:.4f}")
    print(f"RMSE = {rmse:.4f}")
    print(f"R²   = {r2:.4f}")
    print("-"*40)

    return y_pred

In [136]:
#Gradient Boosting (fR,1 e fR,3)
from sklearn.ensemble import GradientBoostingRegressor

gbr_fr1 = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr_fr3 = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr_fr1.fit(X_train, y_train_fr1)
gbr_fr3.fit(X_train, y_train_fr3)

y_pred_gbr_fr1 = evaluate_model(gbr_fr1, X_test, y_test_fr1, "GBR — fR,1")
y_pred_gbr_fr3 = evaluate_model(gbr_fr3, X_test, y_test_fr3, "GBR — fR,3")

 GBR — fR,1
MAE  = 0.5351
RMSE = 0.7781
R²   = 0.8787
----------------------------------------
 GBR — fR,3
MAE  = 0.9973
RMSE = 1.3168
R²   = 0.7449
----------------------------------------

In [137]:
#Equações lineares (aproximação física)
from sklearn.linear_model import LinearRegression

lin_fr1 = LinearRegression()
lin_fr3 = LinearRegression()

lin_fr1.fit(X_train, y_train_fr1)
lin_fr3.fit(X_train, y_train_fr3)

# Avaliação das equações
y_eq_fr1 = evaluate_model(lin_fr1, X_test, y_test_fr1, "Equação Linear — fR,1")
y_eq_fr3 = evaluate_model(lin_fr3, X_test, y_test_fr3, "Equação Linear — fR,3")

 Equação Linear — fR,1
MAE  = 0.6887
RMSE = 0.9020
R²   = 0.8370
----------------------------------------
 Equação Linear — fR,3
MAE  = 1.1901
RMSE = 1.5621
R²   = 0.6410
----------------------------------------

In [139]:
#Mostrar as equações explicitamente
def print_equation(model, feature_names, target_name):
    coef = model.coef_
    intercept = model.intercept_

    eq = f"{target_name} = {intercept:.4f}"
    for c, name in zip(coef, feature_names):
        eq += f" + ({c:.4f} × {name})"

    print(eq)
    print()

print_equation(lin_fr1, X_common.columns, "fR,1")
print_equation(lin_fr3, X_common.columns, "fR,3")

fR,1 = -1.0547 + (0.0650 × fck (resistência)            [MPa]) + (0.0784 × l (comprimento)            [mm]) + (-4.3725 × d (diâmetro            [mm]) + (-0.0214 × l/d      (fator de forma             ) + (6.5176 × Teor de fibra (%)) + (0.6112 × N (ganchos))

fR,3 = -0.8461 + (0.0505 × fck (resistência)            [MPa]) + (0.1765 × l (comprimento)            [mm]) + (-8.1917 × d (diâmetro            [mm]) + (-0.0818 × l/d      (fator de forma             ) + (6.5777 × Teor de fibra (%)) + (2.8456 × N (ganchos))

In [140]:
#DNN (com os mesmos pontos)
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

def build_dnn():
    model = Sequential([
        Dense(32, activation='relu', input_shape=(X_train_s.shape[1],)),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='mse'
    )
    return model

In [141]:
dnn_fr1 = build_dnn()
dnn_fr1.fit(X_train_s, y_train_fr1, epochs=200, verbose=0)

y_pred_dnn_fr1 = dnn_fr1.predict(X_test_s).flatten()

print(" DNN — fR,1")
print(f"MAE  = {mean_absolute_error(y_test_fr1, y_pred_dnn_fr1):.4f}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test_fr1, y_pred_dnn_fr1)):.4f}")
print(f"R²   = {r2_score(y_test_fr1, y_pred_dnn_fr1):.4f}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
 DNN — fR,1
MAE  = 0.5796
RMSE = 0.7685
R²   = 0.8816

In [142]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Treinar a DNN para fR,3
dnn_fr3 = build_dnn()

dnn_fr3.fit(
    X_train_s,
    y_train_fr3,
    epochs=200,
    verbose=0
)

# Previsões
y_pred_dnn_fr3 = dnn_fr3.predict(X_test_s).flatten()

# Avaliação
print(" DNN — fR,3")
print(f"MAE  = {mean_absolute_error(y_test_fr3, y_pred_dnn_fr3):.4f}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test_fr3, y_pred_dnn_fr3)):.4f}")
print(f"R²   = {r2_score(y_test_fr3, y_pred_dnn_fr3):.4f}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
 DNN — fR,3
MAE  = 1.0332
RMSE = 1.3855
R²   = 0.7176

In [143]:
#Random Forest — fR,1 e fR,3
from sklearn.ensemble import RandomForestRegressor

# fR,1
rf_fr1 = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)
rf_fr1.fit(X_train, y_train_fr1)

print("Random Forest — fR,1")
evaluate_model(rf_fr1, X_test, y_test_fr1, "RF — fR,1")

# fR,3
rf_fr3 = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)
rf_fr3.fit(X_train, y_train_fr3)

print("Random Forest — fR,3")
evaluate_model(rf_fr3, X_test, y_test_fr3, "RF — fR,3")

Random Forest — fR,1
 RF — fR,1
MAE  = 0.5660
RMSE = 0.8997
R²   = 0.8378
----------------------------------------
Random Forest — fR,3
 RF — fR,3
MAE  = 1.0207
RMSE = 1.3677
R²   = 0.7248
----------------------------------------

array([ 6.57152107, 11.26576667,  3.2070805 ,  4.54528627,  7.52450302,
        7.35432222,  2.92150331,  5.857281  ,  4.91220552,  5.82284756,
        3.4032489 ,  9.12897455,  2.19866667,  6.6640384 ,  5.20755142,
        6.470373  ,  7.83404843,  5.05469714,  2.7279232 ,  6.62934533,
        7.13232778,  6.83212311,  6.84002486,  5.31965333,  3.28928149,
        5.87497147,  4.48111303,  3.88912574,  3.81536984,  5.15516   ,
        6.83611533,  4.40395423,  3.18218108,  3.80141615,  5.87497147,
        7.48002524,  4.09427573,  3.18218108,  5.15516   ,  3.899487  ,
        3.6083712 ,  8.42997778,  7.48002524,  1.60406667,  2.959513  ,
        2.959513  ,  4.77919562])

In [144]:
#Linear Regrssion — fR,1 e fR,3
from sklearn.linear_model import LinearRegression

# fR,1
lin_fr1 = LinearRegression()
lin_fr1.fit(X_train, y_train_fr1)

print("Regressão Linear — fR,1")
evaluate_model(lin_fr1, X_test, y_test_fr1, "Linear — fR,1")

# fR,3
lin_fr3 = LinearRegression()
lin_fr3.fit(X_train, y_train_fr3)

print("Regressão Linear — fR,3")
evaluate_model(lin_fr3, X_test, y_test_fr3, "Linear — fR,3")

Regressão Linear — fR,1
 Linear — fR,1
MAE  = 0.6887
RMSE = 0.9020
R²   = 0.8370
----------------------------------------
Regressão Linear — fR,3
 Linear — fR,3
MAE  = 1.1901
RMSE = 1.5621
R²   = 0.6410
----------------------------------------

array([ 5.43236221, 15.48129256,  4.19248811,  6.15812303,  6.91698514,
        7.65614357,  2.90996311,  6.93557899,  4.17173179,  4.6872033 ,
        4.53915615,  7.92767304,  2.49433585,  6.8665983 ,  3.64848446,
        4.99818293,  6.9779794 ,  6.19882511,  3.23618333,  6.36742279,
        6.78258403,  5.8774814 ,  5.5329521 ,  4.79300838,  3.47786326,
        4.63881104,  3.83937728,  4.71696428,  5.7702456 ,  4.56905194,
        8.36344365,  4.66271708,  5.38418335,  6.425362  ,  4.63881104,
        6.3513529 ,  4.31168078,  5.38418335,  4.56905194,  4.5188718 ,
        3.29874052,  9.1424986 ,  6.3513529 ,  1.41729302,  3.21510243,
        2.35999832,  4.81469111])

In [151]:
#Tabela comparativa
results = []

def store_results(name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    results.append({
        "Modelo": name,
        "MAE": mean_absolute_error(y_test, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, y_pred)),
        "R²": r2_score(y_test, y_pred)
    })

# fR,1
store_results("GBR — fR,1", gbr_fr1, X_test, y_test_fr1)
store_results("RF — fR,1", rf_fr1, X_test, y_test_fr1)
store_results("Linear — fR,1", lin_fr1, X_test, y_test_fr1)

# fR,3
store_results("GBR — fR,3", gbr_fr3, X_test, y_test_fr3)
store_results("RF — fR,3", rf_fr3, X_test, y_test_fr3)
store_results("Linear — fR,3", lin_fr3, X_test, y_test_fr3)

results_df = pd.DataFrame(results)
display(results_df)

          Modelo     MAE    RMSE      R²
0     GBR — fR,1 0.53508 0.77812 0.87866
1      RF — fR,1 0.56599 0.89971 0.83777
2  Linear — fR,1 0.68869 0.90196 0.83696
3     GBR — fR,3 0.99727 1.31680 0.74490
4      RF — fR,3 1.02069 1.36767 0.72481
5  Linear — fR,3 1.19011 1.56212 0.64100